---
- name: Install Docker and run SonarQube
  hosts: all
  become: true
  tasks:
    # 1. Update the apt package index
    - name: Update apt package index
      apt:
        update_cache: yes
        cache_valid_time: 3600

    # 2. Install Docker
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    # 3. Add user to the Docker group
    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    # 4. Ensure Docker is started and enabled
    - name: Ensure Docker is started and enabled
      systemd:
        name: docker
        state: started
        enabled: yes

    # 5. Set Docker socket permissions
    - name: Set Docker socket permissions
      file:
        path: /var/run/docker.sock
        mode: "0666"

    # 6. Run the SonarQube container
    - name: Run SonarQube container
      docker_container:
        name: sonarqube
        image: sonarqube:lts-community
        state: started
        ports:
          - "9000:9000"
